name: Multi-OS CI

on: [push]

jobs:

  ubuntu-job2:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on Ubuntu2"

