name: Multi-OS CI

on: [push]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on Ubuntu"

  windows-job:
    runs-on: windows-latest
    steps:
      - run: echo "Running on Windows"

  macos-job:
    runs-on: macos-latest
    steps:
      - run: echo "Running on macOS"
